[package]
name = "xtask"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
proc-macro2 = "1.0.82"
quote = "1.0.36"
xshell = "0.2.6"
sourcegen = { path = "../crates/sourcegen" }
